import {
  IconArchive,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowsSort,
  IconBell,
  IconBook,
  IconBriefcase,
  IconBrush,
  IconBuilding,
  IconBulb,
  IconCamera,
  IconChartLine,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClock,
  IconCoffee,
  IconEdit,
  IconFlag,
  IconFlame,
  IconHeart,
  IconHourglass,
  IconMicrophone,
  IconPencil,
  IconPlant,
  IconPlayerPlay,
  IconPlayerStopFilled,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSparkles,
  IconTargetArrow,
  IconTrophy,
  IconUserStar,
  IconUsers,
  IconUsersGroup,
  IconX,
  IconYoga,
  type Icon as TablerIconType,
} from '@tabler/icons-react';

export type IconProps = { size?: number; color?: string; className?: string; stroke?: number };

export const CONTEXT_ICONS: Record<string, TablerIconType> = {
  briefcase: IconBriefcase,
  building: IconBuilding,
  'chart-line': IconChartLine,
  users: IconUsers,
  plant: IconPlant,
  brush: IconBrush,
  bulb: IconBulb,
  'users-group': IconUsersGroup,
  'user-star': IconUserStar,
  camera: IconCamera,
  microphone: IconMicrophone,
  sparkles: IconSparkles,
  heart: IconHeart,
  yoga: IconYoga,
  book: IconBook,
  coffee: IconCoffee,
};

export function ContextIcon({ name, ...props }: { name: string } & IconProps) {
  const Cmp = CONTEXT_ICONS[name] || IconSparkles;
  return <Cmp {...props} />;
}

export {
  IconArchive,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowsSort,
  IconBell,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClock,
  IconEdit,
  IconFlag,
  IconFlame,
  IconHourglass,
  IconPencil,
  IconPlayerPlay,
  IconPlayerStopFilled,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconTargetArrow,
  IconTrophy,
  IconX,
};
